#!/bin/bash
PACKAGE_NAME="$DPKG_MAINTSCRIPT_PACKAGE"
systemctl stop apm-daily-update
systemctl disable apm-daily-update



if [ "$1" = "remove" ] || [ "$1" = "purge" ];then

echo "清理卸载残留"

rm -rf /var/lib/apm/
else
echo "非卸载，跳过清理"
fi



