#!/bin/bash
export PACKAGE_NAME="$DPKG_MAINTSCRIPT_PACKAGE"


case "$1" in
	configure)
/var/lib/apm/$PACKAGE_NAME/files/bin/ace-init
systemctl daemon-reload
systemctl enable apm-daily-update
systemctl start apm-daily-update
systemctl restart apparmor.service || true

        if [ -f /usr/lib/sysctl.d/apm.conf ];then
                sysctl -p /usr/lib/sysctl.d/apm.conf
        fi


;;
	triggered)
		      amber-pm-configure-nvidia-host
            amber-pm-dstore-patch

	;;
esac




true
