#!/bin/bash
export PACKAGE_NAME="$DPKG_MAINTSCRIPT_PACKAGE"


case "$1" in
	triggered)
			amber-pm-dstore-patch
            amber-pm-base-overrider

	;;
	*)
            amber-pm-base-overrider
	;;
esac




true
